### PR TITLE
[Reviewer: SL] Configure signaling netmask

### PR DESCRIPTION
**Pull request by Tom-Rees**
Hi Steve,

Would you mind checking that this looks sensible.

### CODE REVIEW

**Comment by steelyvoid** [comment]
Change looks good, but I noticed something a bit off with the existing command which is that there doesn't appear to be a corresponding "echo" command like the other ip commands, whic presumably is needed for logging purposes.

I'm actually a bit unimpressed with the model that we run a command and then echo the same command to screen - just the sort of thing that could end up confusing people if someone makes a change to the command but forgets to change the echo.  I'd rather we had a model along the lines of

variable = "<command string>"
echo "<command string>"
exec "<command string>"

(not sure what this looks like in bash).

Could you see whether you can get the above model to work and then suggest to Doug that he uses the same model in future bash scripts?  I don't think we should go back and change all the places where this mechanism is used, but we could switch to it each time we find ourselves having to modify one of these lines for some other reason

**Comment by steelyvoid** [comment]
Sorry - github rather unhelpfully munged the contents of those strings out.  Give me a call if its not clear what I'm getting at

**Comment by Tom-Rees** [comment]
Feedback changes made, does that look like what you had in mind?

I thought a function was neater than repeating the same construct but i'm not sure if we can add it to a bash library (if bash has module type things) for use in other scripts.

**Comment by steelyvoid** [comment]
Yes – that looks ideal.  Let just live with the fact that we’ll have to reimplement it for each script

**Comment by Tom-Rees** [comment]
Tested by deploying a new ova containing fixed script. Change looks good.

**Pull request merged**
